framework:
    default_locale: !php/enum App\Shared\Domain\Enum\Iso639_1Code::En->value
    translator:
        default_path: '%kernel.project_dir%/translations'
        paths:
            - '%kernel.project_dir%/src/Shared/Presentation/Resources/translations'
            - '%kernel.project_dir%/src/Account/Presentation/Resources/translations'
            - '%kernel.project_dir%/src/Organization/Presentation/Resources/translations'
        fallbacks:
            - !php/enum App\Shared\Domain\Enum\Iso639_1Code::En->value
            - !php/enum App\Shared\Domain\Enum\Iso639_1Code::De->value
