twig:
    file_name_pattern: "*.twig"

    paths:
        "src/Common/Presentation/Resources/templates": "common.presentation"
        "src/Content/Presentation/Resources/templates": "content.presentation"
        "src/Registration/Presentation/Resources/templates": "registration.presentation"
        "src/Security/Presentation/Resources/templates": "security.presentation"

when@test:
    twig:
        strict_variables: true
