services:
    app:
        build:
            context: .
            dockerfile: docker/app/Dockerfile
        container_name: etfs_app_starter_kit_app
        volumes:
            - .:/var/www
        networks:
            - etfs_app_starter_kit
        environment:
            APP_ENV: prod
        depends_on:
            - mariadb
        restart: unless-stopped

    nginx:
        image: nginx:latest
        container_name: etfs_app_starter_kit_nginx
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - etfs_app_starter_kit
        restart: unless-stopped

    mariadb:
        image: mariadb:12.0.2
        container_name: etfs_app_starter_kit_mariadb
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: etfs_app_starter_kit_prod
            MYSQL_USER: root
            MYSQL_PASSWORD: secret
        volumes:
            - etfs_app_starter_kit_mariadb_data:/var/lib/mysql
        networks:
            - etfs_app_starter_kit
        restart: unless-stopped

networks:
    etfs_app_starter_kit:
        driver: bridge

volumes:
    etfs_app_starter_kit_mariadb_data:
